name: Deploy housing folder to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy files
        run: |
          mkdir docs
          cp -r housing/* docs/
      - name: Commit and push
        run: |
          git config user.name "lucas-caz"
          git config user.email "lucas.caz@gmail.com"
          git add docs
          git commit -m "Deploy"
          git push
